#!/bin/bash
sed ':a;N;$!ba; s/---/---\n\&nbsp;\n<!-- more -->/2' CROSS_JOIN妙用產生各年度1到12月的起始與終止日.md > CROSS_JOIN妙用產生各年度1到12月的起始與終止日.md-changed.txt && mv CROSS_JOIN妙用產生各年度1到12月的起始與終止日.md-changed.txt CROSS_JOIN妙用產生各年度1到12月的起始與終止日.md
sed ':a;N;$!ba; s/---/---\n\&nbsp;\n<!-- more -->/2' CTE妙用-產生出css網格系統.md > CTE妙用-產生出css網格系統.md-changed.txt && mv CTE妙用-產生出css網格系統.md-changed.txt CTE妙用-產生出css網格系統.md
sed ':a;N;$!ba; s/---/---\n\&nbsp;\n<!-- more -->/2' Jquery-DataTable地雷.md > Jquery-DataTable地雷.md-changed.txt && mv Jquery-DataTable地雷.md-changed.txt Jquery-DataTable地雷.md
sed ':a;N;$!ba; s/---/---\n\&nbsp;\n<!-- more -->/2' Jquery-click地雷.md > Jquery-click地雷.md-changed.txt && mv Jquery-click地雷.md-changed.txt Jquery-click地雷.md
sed ':a;N;$!ba; s/---/---\n\&nbsp;\n<!-- more -->/2' NCL-Color-Bar-轉換.md > NCL-Color-Bar-轉換.md-changed.txt && mv NCL-Color-Bar-轉換.md-changed.txt NCL-Color-Bar-轉換.md
sed ':a;N;$!ba; s/---/---\n\&nbsp;\n<!-- more -->/2' NCL-網格資料地雷.md > NCL-網格資料地雷.md-changed.txt && mv NCL-網格資料地雷.md-changed.txt NCL-網格資料地雷.md
sed ':a;N;$!ba; s/---/---\n\&nbsp;\n<!-- more -->/2' OSM簡體轉繁體.md > OSM簡體轉繁體.md-changed.txt && mv OSM簡體轉繁體.md-changed.txt OSM簡體轉繁體.md
sed ':a;N;$!ba; s/---/---\n\&nbsp;\n<!-- more -->/2' asp-net-core-iis-sub-application.md > asp-net-core-iis-sub-application.md-changed.txt && mv asp-net-core-iis-sub-application.md-changed.txt asp-net-core-iis-sub-application.md
sed ':a;N;$!ba; s/---/---\n\&nbsp;\n<!-- more -->/2' asp-net-core-發佈-m3u8.md > asp-net-core-發佈-m3u8.md-changed.txt && mv asp-net-core-發佈-m3u8.md-changed.txt asp-net-core-發佈-m3u8.md
sed ':a;N;$!ba; s/---/---\n\&nbsp;\n<!-- more -->/2' asp-net-core-製作-geojson.md > asp-net-core-製作-geojson.md-changed.txt && mv asp-net-core-製作-geojson.md-changed.txt asp-net-core-製作-geojson.md
sed ':a;N;$!ba; s/---/---\n\&nbsp;\n<!-- more -->/2' chrome-快速切換-url-小技巧.md > chrome-快速切換-url-小技巧.md-changed.txt && mv chrome-快速切換-url-小技巧.md-changed.txt chrome-快速切換-url-小技巧.md
sed ':a;N;$!ba; s/---/---\n\&nbsp;\n<!-- more -->/2' git日常筆記.md > git日常筆記.md-changed.txt && mv git日常筆記.md-changed.txt git日常筆記.md
sed ':a;N;$!ba; s/---/---\n\&nbsp;\n<!-- more -->/2' neovim-整合-vscode-筆記.md > neovim-整合-vscode-筆記.md-changed.txt && mv neovim-整合-vscode-筆記.md-changed.txt neovim-整合-vscode-筆記.md
sed ':a;N;$!ba; s/---/---\n\&nbsp;\n<!-- more -->/2' net-core-LINE-Login-Middleware.md > net-core-LINE-Login-Middleware.md-changed.txt && mv net-core-LINE-Login-Middleware.md-changed.txt net-core-LINE-Login-Middleware.md
sed ':a;N;$!ba; s/---/---\n\&nbsp;\n<!-- more -->/2' net-core-LINE-PAY-API-v3-筆記.md > net-core-LINE-PAY-API-v3-筆記.md-changed.txt && mv net-core-LINE-PAY-API-v3-筆記.md-changed.txt net-core-LINE-PAY-API-v3-筆記.md
sed ':a;N;$!ba; s/---/---\n\&nbsp;\n<!-- more -->/2' net-core-畜牲爬蟲.md > net-core-畜牲爬蟲.md-changed.txt && mv net-core-畜牲爬蟲.md-changed.txt net-core-畜牲爬蟲.md
sed ':a;N;$!ba; s/---/---\n\&nbsp;\n<!-- more -->/2' openlayers地雷.md > openlayers地雷.md-changed.txt && mv openlayers地雷.md-changed.txt openlayers地雷.md
sed ':a;N;$!ba; s/---/---\n\&nbsp;\n<!-- more -->/2' postgresql-補全遺漏的時間區段.md > postgresql-補全遺漏的時間區段.md-changed.txt && mv postgresql-補全遺漏的時間區段.md-changed.txt postgresql-補全遺漏的時間區段.md
sed ':a;N;$!ba; s/---/---\n\&nbsp;\n<!-- more -->/2' powershell-佈署-asp-net-core-到-iis-sub-application.md > powershell-佈署-asp-net-core-到-iis-sub-application.md-changed.txt && mv powershell-佈署-asp-net-core-到-iis-sub-application.md-changed.txt powershell-佈署-asp-net-core-到-iis-sub-application.md
sed ':a;N;$!ba; s/---/---\n\&nbsp;\n<!-- more -->/2' powershell-遠端操作電腦.md > powershell-遠端操作電腦.md-changed.txt && mv powershell-遠端操作電腦.md-changed.txt powershell-遠端操作電腦.md
sed ':a;N;$!ba; s/---/---\n\&nbsp;\n<!-- more -->/2' powershell執行動態sql.md > powershell執行動態sql.md-changed.txt && mv powershell執行動態sql.md-changed.txt powershell執行動態sql.md
sed ':a;N;$!ba; s/---/---\n\&nbsp;\n<!-- more -->/2' powershell日常筆記.md > powershell日常筆記.md-changed.txt && mv powershell日常筆記.md-changed.txt powershell日常筆記.md
sed ':a;N;$!ba; s/---/---\n\&nbsp;\n<!-- more -->/2' visual-studio-vim-mode.md > visual-studio-vim-mode.md-changed.txt && mv visual-studio-vim-mode.md-changed.txt visual-studio-vim-mode.md
sed ':a;N;$!ba; s/---/---\n\&nbsp;\n<!-- more -->/2' vscode-vim-mode.md > vscode-vim-mode.md-changed.txt && mv vscode-vim-mode.md-changed.txt vscode-vim-mode.md
sed ':a;N;$!ba; s/---/---\n\&nbsp;\n<!-- more -->/2' wsl-升級-wsl2.md > wsl-升級-wsl2.md-changed.txt && mv wsl-升級-wsl2.md-changed.txt wsl-升級-wsl2.md
sed ':a;N;$!ba; s/---/---\n\&nbsp;\n<!-- more -->/2' 一些網路高手的Blog.md > 一些網路高手的Blog.md-changed.txt && mv 一些網路高手的Blog.md-changed.txt 一些網路高手的Blog.md
sed ':a;N;$!ba; s/---/---\n\&nbsp;\n<!-- more -->/2' 匯入ShapeFile到MSSQL.md > 匯入ShapeFile到MSSQL.md-changed.txt && mv 匯入ShapeFile到MSSQL.md-changed.txt 匯入ShapeFile到MSSQL.md
sed ':a;N;$!ba; s/---/---\n\&nbsp;\n<!-- more -->/2' 好用的xsd類別產生工具.md > 好用的xsd類別產生工具.md-changed.txt && mv 好用的xsd類別產生工具.md-changed.txt 好用的xsd類別產生工具.md
sed ':a;N;$!ba; s/---/---\n\&nbsp;\n<!-- more -->/2' 將jpg轉換為png8.md > 將jpg轉換為png8.md-changed.txt && mv 將jpg轉換為png8.md-changed.txt 將jpg轉換為png8.md
sed ':a;N;$!ba; s/---/---\n\&nbsp;\n<!-- more -->/2' 常用的vscode-extension.md > 常用的vscode-extension.md-changed.txt && mv 常用的vscode-extension.md-changed.txt 常用的vscode-extension.md
sed ':a;N;$!ba; s/---/---\n\&nbsp;\n<!-- more -->/2' 常用的線上工具.md > 常用的線上工具.md-changed.txt && mv 常用的線上工具.md-changed.txt 常用的線上工具.md
sed ':a;N;$!ba; s/---/---\n\&nbsp;\n<!-- more -->/2' 快速產生批次刪除資料表指令.md > 快速產生批次刪除資料表指令.md-changed.txt && mv 快速產生批次刪除資料表指令.md-changed.txt 快速產生批次刪除資料表指令.md
sed ':a;N;$!ba; s/---/---\n\&nbsp;\n<!-- more -->/2' 快速轉換png為ico.md > 快速轉換png為ico.md-changed.txt && mv 快速轉換png為ico.md-changed.txt 快速轉換png為ico.md
sed ':a;N;$!ba; s/---/---\n\&nbsp;\n<!-- more -->/2' 快速開啟目前目錄的小技巧.md > 快速開啟目前目錄的小技巧.md-changed.txt && mv 快速開啟目前目錄的小技巧.md-changed.txt 快速開啟目前目錄的小技巧.md
sed ':a;N;$!ba; s/---/---\n\&nbsp;\n<!-- more -->/2' 我的-vim-neovim-config.md > 我的-vim-neovim-config.md-changed.txt && mv 我的-vim-neovim-config.md-changed.txt 我的-vim-neovim-config.md
sed ':a;N;$!ba; s/---/---\n\&nbsp;\n<!-- more -->/2' 找出大於1GB的shp.md > 找出大於1GB的shp.md-changed.txt && mv 找出大於1GB的shp.md-changed.txt 找出大於1GB的shp.md
sed ':a;N;$!ba; s/---/---\n\&nbsp;\n<!-- more -->/2' 第一篇文章.md > 第一篇文章.md-changed.txt && mv 第一篇文章.md-changed.txt 第一篇文章.md
sed ':a;N;$!ba; s/---/---\n\&nbsp;\n<!-- more -->/2' 篩選漁業署半徑0-5海浬的人工魚礁.md > 篩選漁業署半徑0-5海浬的人工魚礁.md-changed.txt && mv 篩選漁業署半徑0-5海浬的人工魚礁.md-changed.txt 篩選漁業署半徑0-5海浬的人工魚礁.md
sed ':a;N;$!ba; s/---/---\n\&nbsp;\n<!-- more -->/2' 運用powershell快速轉換sql-server查詢結果為json.md > 運用powershell快速轉換sql-server查詢結果為json.md-changed.txt && mv 運用powershell快速轉換sql-server查詢結果為json.md-changed.txt 運用powershell快速轉換sql-server查詢結果為json.md
sed ':a;N;$!ba; s/---/---\n\&nbsp;\n<!-- more -->/2' 遞迴找檔案.md > 遞迴找檔案.md-changed.txt && mv 遞迴找檔案.md-changed.txt 遞迴找檔案.md
